# Generated by Django 3.0.7 on 2020-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
